### PR TITLE
List KoboldCpp as compatible

### PR DESCRIPTION
**Pull request by henk717**
KoboldCpp is a great fit for TaleMate, it supports fast local generations across a variety of machines including the cloud and is compatible with both text and image gen trough the OpenAI API, and A1111 API (Possibly even the TextGenWebUI one since they originally emulated the KoboldAI API).

I have tested it on a local installation and everything was working great, if you'd like to verify you can verify against our public dev instance available at https://koboldai-koboldcpp-tiefighter.hf.space/ (This space is also used by others, if it rejects prompts its because its currently overused)

Unique is the fact it can also do Image Generation, it has ROCm and Vulkan supported and both popular cloud providers have easy templates. It also has context shifting that would help against processing times, but I have noticed the prompting in talemate is quite complex so context shifting may not be effective for this project.

### CODE REVIEW

**Comment by henk717** [comment]
Small update, A1111 may be hanging but for text gen it still works great. You will have to do some research as to why the A1111 api URL is failing. Could be on my end.

**Comment by vegu-ai-tools** [comment]
Thanks - i will check it out.

**Comment by henk717** [comment]
For the best results enable KoboldCpp's multiuser mode which allows requests to be queued up. Will help with possible conflicts from the various tasks you send.

**Comment by vegu-ai-tools** [comment]
i am finding that this sort of works - but there seem to be issues with passing some generation parameters with the prompts - i haven't looked closely at the api endpoints at this point, but `max_tokens` for one seems to be ignored completely - which talemate needs to be able to set on a per inference request basis. 

Ideally it'd be able to do temperature per request as well, but that's less crucial then it honoring the max tokens - for example right now i am looking at it generating 2048 tokens worth of world state update data - which is way too much.

Ill need to look at this more closely when i have more time - currently i am thinking a dedicated koboldcpp client might be more reasonable. It seems to work well enough for dialogue generation, but some of the other stuff just breaks down completely for me.

For now, i am opening a new issue at https://github.com/vegu-ai/talemate/issues/105.

PS: Testing with llama-3 8b fp16

**Comment by vegu-ai-tools** [comment]
On further inspection it seems it honors the max_tokens, but i still keep running into run-away issues - which i suspect might be the llama-8b eos token issue i guess - trying with a different model

**Comment by henk717** [comment]
In the entire llamacpp ecosystem you will currently find a lot of changes happening with tokenization so you'd need a very up to date Llama3 model to verify. I recommend testing with something like Llama2 and Mistral instead since those are more established, then you know if its our implementation and rule out bad conversions with the models. I tested with Fimbulvetr 11B myself and didn't run into any issues.

**Comment by vegu-ai-tools** [comment]
thanks, I am having much better luck after switching away to konoichi.

also tested dolphin-2.8-mistral-7b with chatml template 

so that all looks good to me now :)

looking at the PR, the vast.ai / runpod links don't seem to do anything - i assume they are supposed to select templates?

**Pull request merged**
